<?php


class UpdateUserView extends UpdateAPIView {

//	private function updateUser( $user ): UserResult {
//		global $CMD_UPDATE_USER;
//		$ctx = new ExecutionContext();
//		$ctx->setValue( 'username', $username );
//		$ctx->setValue( 'password', $password );
//
//		return Executor::getInstance()->execute( $CMD_LOGIN_USER, $ctx );
//	}
//
//	public function patch( Request $request ): AbstractResponse {
//
//		$guard = new Guard();
//		$user = $guard->getSessionUser();
//
//		if ($user === null) {
//			return new UnauthorizedResponse();
//		}
//
//		return parent::patch( $request ); // TODO: Change the autogenerated stub
//	}


	protected function getCommandKey(): string {
		// TODO: Implement getCommandKey() method.
	}

	protected function getSerializer(): AbstractSerializer {
		// TODO: Implement getSerializer() method.
	}
}