<?php

include_once __DIR__.'/abstract.php';
include_once __DIR__.'/response/RawFileResponse.php';


abstract class ListAPIView extends AbstractModelAPIView {

	public function get( Request $request ): AbstractResponse {
		// TODO: Implement get() method.
	}
}


abstract class CreateAPIView extends AbstractModelAPIView {

	public function post(Request $request): AbstractResponse {

	}

}


abstract class UpdateAPIView extends AbstractModelAPIView {

	public function patch( Request $request ): AbstractResponse {

		$guard = new Guard();
		$user = $guard->getSessionUser();

		if ($user === null) {
			return new UnauthorizedResponse();
		}

		return parent::patch( $request ); // TODO: Change the autogenerated stub
	}
}


abstract class DeleteAPIView extends AbstractModelAPIView {

}


class NotFoundView extends  AbstractAPIView {
	public function get(Request $request): AbstractResponse {
		return new NotFoundResponse();
	}
}

class RawFileView extends  AbstractAPIView {

	private $filePath;
	private $contentType;

	public function __construct($filePath, $contentType) {
		parent::__construct();
		$this->filePath = $filePath;
		$this->contentType = $contentType;
	}

	public function get( Request $request ): AbstractResponse {
		return new RawFileResponse(200, file_get_contents($this->filePath), $this->contentType);
	}
}

class FrontendView extends AbstractAPIView {
	public function get( Request $request): AbstractResponse {
		global $SETTINGS;

		if (file_exists($SETTINGS['frontend-entry-path'])) {
			return new RawFileResponse(200, file_get_contents($SETTINGS['frontend-entry-path']), 'text/html');
		} else {
			return new NotFoundResponse();
		}
	}
}