<?php

include_once __DIR__.'/abstract.php';


abstract class ListAPIView extends AbstractModelAPIView {

	public function get( Request $request ): AbstractResponse {
		// TODO: Implement get() method.
	}
}


abstract class CreateAPIView extends AbstractModelAPIView {

	public function post(Request $request): AbstractResponse {

	}

}


abstract class UpdateAPIView extends AbstractModelAPIView {

	public function patch( Request $request ): AbstractResponse {

		$guard = new Guard();
		$user = $guard->getSessionUser();

		if ($user === null) {
			return new UnauthorizedResponse();
		}

		return parent::patch( $request ); // TODO: Change the autogenerated stub
	}
}


abstract class DeleteAPIView extends AbstractModelAPIView {

}