---
- hosts: production
  remote_user: developer

  vars:
    remote_basedir: "/home/developer/sites/samworks-ffhs-deep-slumber-live/backend/"
    project_id: samworks-ffhs-deep-slumber-live

  tasks:
  - name: Create Base Dir
    file:
      path: "{{ remote_basedir }}"
      state: directory

  - name: Git pull
    git:
      repo: ssh://git@alphacentauri-samworks.synology.me:30001/samworks/ffhs-deep-slumber-backend.git
      dest: "{{ remote_basedir }}"
      version: "production"

  - name: Create Generated Dir
    file:
      path: "{{ remote_basedir }}/generated"
      state: directory

  - name: Install Composer
    shell: ". ./scripts/install-composer.sh"
    args:
      chdir: "{{ remote_basedir }}"

  - name: Install Dependencies
    command: chdir={{ remote_basedir }} php composer.phar install

  - name: Update Propel config
    command: chdir={{ remote_basedir }} ./vendor/bin/propel config:convert

  - name: Execute Database mirations
    command: chdir={{ remote_basedir }} ./vendor/bin/propel migrate

  - name: Build Generated Database models
    command: chdir={{ remote_basedir }} ./vendor/bin/propel model:build

  - name: Generate autoload
    command: chdir={{ remote_basedir }} php composer.phar dump-autoload