---
- hosts: production
  remote_user: developer

  vars:
    remote_basedir: /home/developer/sites/samworks-ffhs-deep-slumber-live/backend

  tasks:
    - name: Create Base Dir
      file:
        path: "{{ remote_basedir }}"
        state: directory

    - name: Create Generated Dir
      file:
        path: "{{ remote_basedir }}"/generated
        state: directory

    - name: Git pull
      git:
        repo: ssh://git@alphacentauri-samworks.synology.me:30001/samworks/ffhs-deep-slumber-backend.git
        dest: "{{ remote_basedir }}"
        version: "production"

    - name: Install Composer
      command: chdir={{ remote_basedir }} source ./scripts/install-composer.sh

    - name: Install Dependencies
      composer:
        command: install
        working_dir: {{ remote_basedir }}