<?php

include_once __DIR__.'/../../common/serializers/serializer.php';


class UserSerializer extends AbstractSerializer {

	private static $FIELD_ID = 'id';
	private static $FIELD_USERNAME = 'username';
	private static $FIELD_FIRST_NAME = 'first_name';
	private static $FIELD_LAST_NAME = 'last_name';


	public function __construct( $raw_data, $instance=null ) {
		parent::__construct( $raw_data, $instance );
		$this->REQUIRED_FIELDS = [
			UserSerializer::$FIELD_ID
		];
	}

	public function serialize(): array {
		if ($this->instance === null) {
			return array();
		}

		$serialized = array();
		$serialized['id'] = $this->instance->getId();
		$serialized['username'] = $this->instance->getUsername();
		$serialized['first_name'] = $this->instance->getfirst_name();
		$serialized['last_name'] = $this->instance->getlast_name();
		$serialized['email'] = $this->instance->getEmail();

		return $serialized;
	}

	public function is_valid(): bool {
		return parent::is_valid(); // TODO: Change the autogenerated stub
	}
}
